// ============================================
// DATASET & FILES
// ============================================

export interface Dataset {
  id: string
  name: string
  description?: string
  canonicalSchema: ColumnSchema[] | null
  createdAt: Date
  updatedAt: Date
  fileCount: number
  rowCount: number
}

export interface ColumnSchema {
  id: string // Column identifier (same as name for now, but allows flexibility)
  label: string // Display name for UI
  type: 'string' | 'number' | 'date' | 'boolean'
  role: 'dimension' | 'metric' // Semantic role for visualization
  nullable?: boolean
}

export interface DataFile {
  id: string
  datasetId: string
  originalFilename: string
  displayName: string
  uploadedAt: Date
  columnSchema: ColumnSchema[]
  schemaFingerprint: string
  rowCount: number
  periodStart?: Date
  periodEnd?: Date
  tags?: string[]
}

export interface DataRow {
  id: string
  datasetId: string
  fileId: string
  rowNumber: number
  parsedDate?: Date
  data: Record<string, unknown>
}

export interface ParsedCSV {
  headers: string[]
  rows: Record<string, unknown>[]
  schema: ColumnSchema[]
  schemaFingerprint: string
}

// ============================================
// CHART CONFIGURATION
// ============================================

export type ChartType = 'line' | 'bar' | 'area' | 'pie' | 'scatter'
export type AggregationType = 'sum' | 'avg' | 'count' | 'min' | 'max'
export type BucketType = 'day' | 'week' | 'month'

export interface ChartConfig {
  chartType: ChartType
  xAxis: string
  yAxis: string[]
  groupBy?: string | null
  aggregation?: AggregationType
  dateRange?: {
    start: string
    end: string
  } | null
  bucket?: BucketType | null
  filters?: Array<{
    column: string
    op: 'eq' | 'in' | 'gte' | 'lte'
    value: string | string[]
  }>
}

// Legacy ChartConfig for backwards compatibility
export interface LegacyChartConfig {
  type: 'line' | 'bar' | 'area' | 'pie' | 'scatter'
  xAxis: string
  yAxis: string[]
  groupBy?: string
  filters?: Record<string, unknown>
}

// ============================================
// DASHBOARD & PANELS
// ============================================

// UI-only configuration (not persisted to DB)
export interface DashboardLayoutConfig {
  columns: 1 | 2 | 3 | 4 // Number of columns in grid
  rowHeight: number // Row height in pixels
  gap: number // Gap between panels in pixels
}

// Default layout settings
export const DEFAULT_DASHBOARD_LAYOUT: DashboardLayoutConfig = {
  columns: 2,
  rowHeight: 300,
  gap: 16,
}

export interface DashboardPanel {
  id: string
  dashboardId: string
  title: string
  config: ChartConfig
  sortOrder: number // Simple ordering (panels render in this order)
  createdAt: Date
  updatedAt: Date
}

export interface Dashboard {
  id: string
  userId: string
  datasetId: string
  name: string
  description?: string
  createdAt: Date
  updatedAt: Date
}

// Dashboard with all panels included
export interface DashboardWithPanels extends Dashboard {
  panels: DashboardPanel[]
}

// Dashboard with dataset info (for list views)
export interface DashboardWithDataset extends Dashboard {
  dataset: {
    id: string
    name: string
    rowCount: number
  }
  panelCount: number
}

// ============================================
// AI CHAT TYPES
// ============================================

export interface AIChatSession {
  id: string
  userId: string
  datasetId: string
  title: string | null
  createdAt: Date
  updatedAt: Date
}

export interface AIChatMessage {
  id: string
  sessionId: string
  role: 'user' | 'assistant' | 'system' | 'tool'
  content: string
  toolCalls?: ToolCallResult[]
  chartConfig?: ChartConfig | null
  createdAt: Date
}

export interface ToolCallResult {
  toolName: string
  args: Record<string, unknown>
  result: unknown
}

// ============================================
// AI TOOL SCHEMAS
// ============================================

// The chart config generated by AI tools
export interface AIChartConfig {
  chartType: ChartType
  xAxis: string
  yAxis: string[]
  groupBy?: string | null
  bucket?: BucketType | null
  dateRange?: {
    start: string
    end: string
  } | null
  aggregation?: AggregationType
  title?: string
}

// Context retrieved via RAG
export interface RAGContext {
  content: string
  contentType: 'schema' | 'sample' | 'description' | 'statistics'
  metadata: Record<string, unknown>
  similarity: number
}
